# Fly.io deployment configuration for BuildExpenseTracker API
app = "buildexpensetracker-api-dev"
primary_region = "sjc"

[build]
  dockerfile = "./backend/Dockerfile"

[env]
  ENV = "development"
  PORT = "8000"
  PYTHONPATH = "/app"
  SEED = "true"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

  [http_service.checks]
    [http_service.checks.healthz]
      grace_period = "10s"
      interval = "30s"
      method = "GET"
      timeout = "5s"
      path = "/healthz"

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 512

# Set these secrets via: fly secrets set KEY=value
# Required secrets:
# - SUPABASE_URL
# - SUPABASE_ANON_KEY
# - SUPABASE_SERVICE_ROLE_KEY  
# - DATABASE_URL
# - ALLOWED_ORIGINS
