# Render.com deployment configuration for BuildExpenseTracker
services:
  - type: web
    name: buildexpensetracker-api-dev
    env: docker
    dockerfilePath: ./backend/Dockerfile
    dockerContext: ./backend
    plan: starter
    region: oregon
    branch: dev
    buildCommand: ""
    startCommand: "uvicorn main:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: ENV
        value: development
      - key: PORT
        value: 8000
      - key: PYTHONPATH
        value: /app
      - key: SEED
        value: "true"
      # These should be set in Render dashboard as secrets:
      # - SUPABASE_URL
      # - SUPABASE_ANON_KEY  
      # - SUPABASE_SERVICE_ROLE_KEY
      # - DATABASE_URL
      # - ALLOWED_ORIGINS (comma-separated list)
    healthCheckPath: /healthz
    
  - type: web
    name: buildexpensetracker-app-dev
    env: static
    buildCommand: npm ci && npm run build
    staticPublishPath: ./dist
    pullRequestPreviewsEnabled: true
    branch: dev
    rootDir: frontend
    envVars:
      - key: VITE_API_BASE_URL
        value: https://buildexpensetracker-api-dev.onrender.com
      # These should be set in Render dashboard:
      # - VITE_SUPABASE_URL
      # - VITE_SUPABASE_ANON_KEY
